services:
  nodejs-server:
    image: souravkumarverma123/chaicode_deploy
    deploy:
      replicas: 3
    networks:
      - chaicode-internal

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - chaicode-internal

networks:
  chaicode-internal:
    driver: bridge